// SPDX-FileCopyrightText: 2026 Ashon
// SPDX-License-Identifier: MIT

// Package provisioner runs the bootstrap script on a host and reports on it.
//
// kubeadm init can take minutes, far longer than a reconcile should block for.
// Rather than tracking in-flight work in controller memory, the run is detached
// on the host itself and its outcome is written to disk. Every piece of state the
// controller needs is therefore readable from the host, which keeps reconciles
// cheap and makes the work survive a controller restart or a clusterctl move.
package provisioner

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"strconv"
	"strings"

	"github.com/Ashon/kgenesis/internal/ssh"
)

// Host paths. State lives under /var/lib so it survives a reboot: /run is tmpfs,
// and losing the marker there would make the controller re-run kubeadm init on a
// node that had already joined.
const (
	stateDir     = "/var/lib/kgenesis"
	scriptPath   = stateDir + "/bootstrap.sh"
	runnerPath   = stateDir + "/run.sh"
	checksumPath = stateDir + "/checksum"
	exitCodePath = stateDir + "/exit-code"
	LogPath      = "/var/log/kgenesis-bootstrap.log"
)

// Phase is the state of the bootstrap run on a host.
type Phase string

const (
	// PhaseIdle means no run has been started for the requested bootstrap data.
	PhaseIdle Phase = "Idle"
	// PhaseRunning means the script is executing.
	PhaseRunning Phase = "Running"
	// PhaseSucceeded means the script exited 0.
	PhaseSucceeded Phase = "Succeeded"
	// PhaseFailed means the script exited non-zero.
	PhaseFailed Phase = "Failed"
)

// State is what the host reports about its bootstrap run.
type State struct {
	Phase Phase

	// Checksum identifies the bootstrap data the host last acted on. When it
	// differs from the desired checksum the phase is reported as Idle, so new
	// bootstrap data triggers a fresh run.
	Checksum string

	ExitCode int

	// LogTail is the end of the bootstrap log, populated when the run failed.
	LogTail string
}

// Checksum is the stable identity of a piece of bootstrap data.
func Checksum(data []byte) string {
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:])
}

// Status reports where the host is with respect to the desired bootstrap data.
func Status(ctx context.Context, c *ssh.Client, desiredChecksum string) (State, error) {
	recorded, err := readFile(ctx, c, checksumPath)
	if err != nil {
		return State{}, err
	}
	if recorded == "" || recorded != desiredChecksum {
		// Either nothing ran, or what ran was for different bootstrap data.
		return State{Phase: PhaseIdle, Checksum: recorded}, nil
	}

	exitCode, err := readFile(ctx, c, exitCodePath)
	if err != nil {
		return State{}, err
	}
	if exitCode == "" {
		return State{Phase: PhaseRunning, Checksum: recorded}, nil
	}

	code, err := strconv.Atoi(exitCode)
	if err != nil {
		return State{}, fmt.Errorf("host wrote an unreadable exit code %q to %s", exitCode, exitCodePath)
	}
	if code == 0 {
		return State{Phase: PhaseSucceeded, Checksum: recorded}, nil
	}

	logTail, err := tailLog(ctx, c)
	if err != nil {
		return State{}, err
	}
	return State{Phase: PhaseFailed, Checksum: recorded, ExitCode: code, LogTail: logTail}, nil
}

// Start uploads the script and launches it detached. The checksum is written
// only after the script is in place, so an interrupted upload reads back as Idle
// and is simply retried rather than being mistaken for a finished run.
func Start(ctx context.Context, c *ssh.Client, script []byte, checksum string) error {
	if err := preflight(ctx, c); err != nil {
		return err
	}

	// Clear the previous outcome first: a stale exit code next to a fresh checksum
	// would be read as a completed run.
	if _, err := c.Run(ctx, fmt.Sprintf("install -d -m 0700 %s && rm -f %s %s",
		stateDir, exitCodePath, checksumPath)); err != nil {
		return fmt.Errorf("prepare %s: %w", stateDir, err)
	}

	if err := c.WriteFile(ctx, scriptPath, script, "0700"); err != nil {
		return err
	}

	runner := fmt.Sprintf(`#!/usr/bin/env bash
# Generated by kgenesis. Runs the bootstrap script and records its outcome.
exec >>%s 2>&1
echo "=== kgenesis bootstrap started $(date -Is) checksum=%s ==="
set +e
bash %s
code=$?
set -e
echo "=== kgenesis bootstrap finished $(date -Is) exit=${code} ==="
printf '%%s' "${code}" > %s
`, LogPath, checksum, scriptPath, exitCodePath)

	if err := c.WriteFile(ctx, runnerPath, []byte(runner), "0700"); err != nil {
		return err
	}

	if err := c.WriteFile(ctx, checksumPath, []byte(checksum), "0600"); err != nil {
		return err
	}

	// setsid detaches the run from this SSH session so closing the connection does
	// not take kubeadm down with it.
	launch := fmt.Sprintf("setsid nohup %s </dev/null >/dev/null 2>&1 & disown; true", runnerPath)
	if _, err := c.Run(ctx, launch); err != nil {
		return fmt.Errorf("launch bootstrap: %w", err)
	}
	return nil
}

// requiredCommands are what the rendered bootstrap script assumes exist.
// Checking up front turns an obscure mid-kubeadm failure into a clear message.
//
// kubeadm and kubelet are on the list because kgenesis does not install them. A
// host without them passes every other check and then fails several minutes
// into a rollout, wearing the name of whatever kubeadm was doing at the time.
var requiredCommands = []string{
	"bash", "base64", "install", "setsid", "systemctl", "kubeadm", "kubelet",
}

func preflight(ctx context.Context, c *ssh.Client) error {
	res, err := c.Run(ctx, "id -u")
	if err != nil {
		return fmt.Errorf("check privileges: %w", err)
	}
	if strings.TrimSpace(res.Stdout) != "0" {
		return fmt.Errorf("kgenesis needs to connect as root; the ssh user resolved to uid %s",
			strings.TrimSpace(res.Stdout))
	}

	var missing []string
	for _, cmd := range requiredCommands {
		if _, err := c.Run(ctx, "command -v "+cmd); err != nil {
			var exitErr *ssh.ExitError
			if errors.As(err, &exitErr) {
				missing = append(missing, cmd)
				continue
			}
			return fmt.Errorf("probe for %s: %w", cmd, err)
		}
	}
	if len(missing) > 0 {
		return fmt.Errorf("host is missing required command(s): %s", strings.Join(missing, ", "))
	}
	return nil
}

// Reset returns a host to a state where it can be bootstrapped again. It is best
// effort by design: a half-joined node must still be releasable.
func Reset(ctx context.Context, c *ssh.Client) error {
	script := `#!/usr/bin/env bash
# Generated by kgenesis. Undoes a kubeadm bootstrap so the host can be reused.
set -uo pipefail

# kube-vip puts the control plane VIP on an interface itself, and kubeadm reset
# knows nothing about it. The address has to be read before reset removes the
# static pod that names it. Left behind, this host keeps answering for an
# endpoint it no longer serves, and the next node joining through that VIP
# reaches this one instead of the control plane.
vip=
if [ -f /etc/kubernetes/manifests/kube-vip.yaml ]; then
  vip="$(awk '/name: address/ { getline; gsub(/["[:space:]]/, "", $0); sub(/^value:/, "", $0); print; exit }' \
    /etc/kubernetes/manifests/kube-vip.yaml)"
fi

if command -v kubeadm >/dev/null 2>&1; then
  kubeadm reset --force || true
fi

if [ -n "${vip}" ] && command -v ip >/dev/null 2>&1; then
  ip -o -4 addr show | awk -v vip="${vip}" '$4 ~ "^"vip"/" { print $2, $4 }' |
    while read -r iface addr; do
      ip addr del "${addr}" dev "${iface}" 2>/dev/null || true
    done
fi

systemctl stop kubelet 2>/dev/null || true

if command -v crictl >/dev/null 2>&1; then
  crictl rm --force --all 2>/dev/null || true
fi

if command -v ip >/dev/null 2>&1; then
  for link in cni0 flannel.1 kube-ipvs0 cilium_host cilium_net cilium_vxlan; do
    ip link delete "${link}" 2>/dev/null || true
  done
fi

rm -rf /etc/cni/net.d /var/lib/cni /etc/kubernetes /var/lib/etcd
rm -rf /run/kubeadm /run/cluster-api
rm -rf ` + stateDir + `

if command -v iptables >/dev/null 2>&1; then
  iptables -F 2>/dev/null || true
  iptables -t nat -F 2>/dev/null || true
  iptables -t mangle -F 2>/dev/null || true
fi

exit 0
`
	const resetPath = "/tmp/kgenesis-reset.sh"
	if err := c.WriteFile(ctx, resetPath, []byte(script), "0700"); err != nil {
		return err
	}
	if _, err := c.Run(ctx, "bash "+resetPath+" && rm -f "+resetPath); err != nil {
		return fmt.Errorf("reset host: %w", err)
	}
	return nil
}

// readFile returns the file's contents, or "" when it does not exist. Any other
// failure is an error: treating an unreadable file as absent would let a broken
// connection look like "nothing has run here".
func readFile(ctx context.Context, c *ssh.Client, path string) (string, error) {
	res, err := c.Run(ctx, fmt.Sprintf("if [ -f %q ]; then cat %q; fi", path, path))
	if err != nil {
		return "", fmt.Errorf("read %s: %w", path, err)
	}
	return strings.TrimSpace(res.Stdout), nil
}

const logTailLines = 40

func tailLog(ctx context.Context, c *ssh.Client) (string, error) {
	res, err := c.Run(ctx, fmt.Sprintf("if [ -f %q ]; then tail -n %d %q; fi", LogPath, logTailLines, LogPath))
	if err != nil {
		return "", fmt.Errorf("read %s: %w", LogPath, err)
	}
	return strings.TrimSpace(res.Stdout), nil
}
