---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kgenesis-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  - clusters/status
  - machines
  - machines/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.kgenesis.io
  resources:
  - hostclusters
  - hostmachines
  - hosts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.kgenesis.io
  resources:
  - hostclusters/status
  - hostmachines/status
  - hosts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infrastructure.kgenesis.io
  resources:
  - hostmachinetemplates
  verbs:
  - get
  - list
  - watch
