#!/usr/bin/env bash
# Assembles the provider components that `kgenesis init` applies, and embeds them
# in the CLI so a genesis node needs no network access to a manifest repository.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="${root}/internal/assets/provider-components.yaml"

{
  echo "# Generated by hack/build-components.sh. Do not edit."
  echo "# Source: config/crd, config/rbac, config/manager"

  for file in "${root}"/config/crd/*.yaml "${root}"/config/rbac/*.yaml "${root}"/config/manager/*.yaml; do
    echo "---"
    # Strip a leading document separator so the output has exactly one per object.
    sed -e '1{/^---$/d;}' "${file}"
  done
} > "${out}"

echo "Wrote ${out}"
