package cloudinit

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"strings"
	"testing"

	"github.com/blang/semver/v4"
	bootstrapv1 "sigs.k8s.io/cluster-api/api/bootstrap/kubeadm/v1beta2"
	"sigs.k8s.io/cluster-api/bootstrap/kubeadm/pkg/cloudinit"
	"sigs.k8s.io/cluster-api/util/secret"
)

// TestRenderCABPKControlPlaneInit feeds the renderer output generated by CABPK
// itself, so a change to the upstream cloud-config template shows up here rather
// than on a half-bootstrapped host.
func TestRenderCABPKControlPlaneInit(t *testing.T) {
	userData, err := cloudinit.NewInitControlPlane(&cloudinit.ControlPlaneInput{
		BaseUserData: cloudinit.BaseUserData{
			PreKubeadmCommands:  []string{"echo pre"},
			PostKubeadmCommands: []string{"echo post"},
			KubernetesVersion:   semver.MustParse("1.34.1"),
			AdditionalFiles: []bootstrapv1.File{{
				Path:        "/etc/kgenesis/marker",
				Owner:       "root:root",
				Permissions: "0644",
				Content:     "hello\nworld\n",
			}},
		},
		Certificates:         secret.Certificates{},
		ClusterConfiguration: "apiVersion: kubeadm.k8s.io/v1beta4\nkind: ClusterConfiguration\n",
		InitConfiguration:    "apiVersion: kubeadm.k8s.io/v1beta4\nkind: InitConfiguration\n",
	})
	if err != nil {
		t.Fatalf("generate CABPK user data: %v", err)
	}

	script, err := Render(userData, Options{})
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	got := string(script)

	for _, want := range []string{
		"set -euo pipefail",
		"/run/kubeadm/kubeadm.yaml",
		"/etc/kgenesis/marker",
		"echo pre",
		"kubeadm init --config /run/kubeadm/kubeadm.yaml",
		"echo post",
		SentinelPath,
	} {
		if !strings.Contains(got, want) {
			t.Errorf("rendered script is missing %q\n---\n%s", want, got)
		}
	}
}

// extractPayload returns the decoded content the script writes to path.
func extractPayload(t *testing.T, script, path string) string {
	t.Helper()

	marker := "> '" + path + "'\n"
	i := strings.Index(script, marker)
	if i < 0 {
		t.Fatalf("script does not write %s\n---\n%s", path, script)
	}
	rest := script[i+len(marker):]

	j := strings.Index(rest, heredocDelimiter)
	if j < 0 {
		t.Fatalf("heredoc for %s is not terminated\n---\n%s", path, script)
	}

	decoded, err := base64.StdEncoding.DecodeString(strings.Join(strings.Fields(rest[:j]), ""))
	if err != nil {
		t.Fatalf("payload for %s is not valid base64: %v", path, err)
	}
	return string(decoded)
}

func TestRenderWriteFileEncodings(t *testing.T) {
	var gz bytes.Buffer
	zw := gzip.NewWriter(&gz)
	if _, err := zw.Write([]byte("compressed payload")); err != nil {
		t.Fatalf("gzip write: %v", err)
	}
	if err := zw.Close(); err != nil {
		t.Fatalf("gzip close: %v", err)
	}

	userData := `#cloud-config
write_files:
-   path: /tmp/plain
    permissions: '0600'
    owner: root:root
    content: |
      line one
      line two
-   path: /tmp/b64
    encoding: "base64"
    content: ` + base64.StdEncoding.EncodeToString([]byte("decoded from base64")) + `
-   path: /tmp/gz
    encoding: "gzip+base64"
    content: ` + base64.StdEncoding.EncodeToString(gz.Bytes()) + `
-   path: /tmp/appended
    append: true
    content: more
`

	script, err := Render([]byte(userData), Options{})
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	got := string(script)

	for _, want := range []string{
		"chmod '0600' '/tmp/plain'",
		"chown 'root:root' '/tmp/plain'",
		">> '/tmp/appended'",
		"install -d -m 0755 '/tmp'",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("rendered script is missing %q\n---\n%s", want, got)
		}
	}

	for path, want := range map[string]string{
		"/tmp/plain": "line one\nline two\n",
		"/tmp/b64":   "decoded from base64",
		"/tmp/gz":    "compressed payload",
	} {
		if got := extractPayload(t, string(script), path); got != want {
			t.Errorf("%s: got %q, want %q", path, got, want)
		}
	}
}

func TestRenderRejectsUnsupportedDirectives(t *testing.T) {
	const userData = `#cloud-config
runcmd:
  - echo hi
users:
  - name: alice
disk_setup:
  /dev/sdb: {}
`
	_, err := Render([]byte(userData), Options{})
	if err == nil {
		t.Fatal("expected an error for unsupported directives, got nil")
	}
	for _, want := range []string{"disk_setup", "users"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("error does not name %q: %v", want, err)
		}
	}
}

func TestRenderArgvCommand(t *testing.T) {
	const userData = `#cloud-config
runcmd:
  - [ systemctl, restart, "kubelet" ]
  - echo "a string; runs through the shell"
`
	script, err := Render([]byte(userData), Options{})
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	got := string(script)

	if !strings.Contains(got, "'systemctl' 'restart' 'kubelet'") {
		t.Errorf("argv form was not quoted\n---\n%s", got)
	}
	if !strings.Contains(got, `echo "a string; runs through the shell"`) {
		t.Errorf("string form was not passed through verbatim\n---\n%s", got)
	}
}

func TestRenderInjectsProviderID(t *testing.T) {
	const userData = `#cloud-config
runcmd:
  - kubeadm join --config /run/kubeadm/kubeadm-join-config.yaml
`
	const providerID = "kgenesis://default/cp-1"

	script, err := Render([]byte(userData), Options{ProviderID: providerID})
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	got := string(script)

	if !strings.Contains(got, kubeletDropInPath) {
		t.Errorf("drop-in path is missing\n---\n%s", got)
	}
	if !strings.Contains(got, "systemctl daemon-reload") {
		t.Errorf("daemon-reload is missing\n---\n%s", got)
	}

	want := "[Service]\nEnvironment=\"KUBELET_EXTRA_ARGS=--provider-id=" + providerID + "\"\n"
	if got := extractPayload(t, string(script), kubeletDropInPath); got != want {
		t.Errorf("drop-in contents: got %q, want %q", got, want)
	}

	// The drop-in has to be in place before kubeadm starts the kubelet.
	if strings.Index(got, kubeletDropInPath) > strings.Index(got, "kubeadm join") {
		t.Errorf("drop-in is written after kubeadm runs\n---\n%s", got)
	}
}

func TestRenderWithoutProviderIDEmitsNoDropIn(t *testing.T) {
	script, err := Render([]byte("#cloud-config\nruncmd:\n  - \"true\"\n"), Options{})
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if strings.Contains(string(script), kubeletDropInPath) {
		t.Errorf("drop-in was emitted without a provider ID\n---\n%s", script)
	}
}
