// SPDX-FileCopyrightText: 2026 Ashon
// SPDX-License-Identifier: MIT

// Package cloudinit turns the cloud-config CABPK produces into a single bash
// script that kgenesis executes over SSH.
//
// Pre-provisioned hosts have no metadata service, so nothing would hand the
// cloud-config to a cloud-init daemon even where one is installed. Rendering the
// directives CABPK actually emits into one script keeps the host requirements at
// "bash and coreutils", makes the run reproducible, and leaves an artifact an
// operator can read and re-run by hand.
package cloudinit

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"sort"
	"strings"

	"sigs.k8s.io/yaml"
)

// SentinelPath is the file CABPK's generated commands write on success. Its
// presence is how kgenesis tells an already-bootstrapped host from a fresh one.
const SentinelPath = "/run/cluster-api/bootstrap-success.complete"

// Supported top level cloud-config directives.
var supported = map[string]bool{
	"write_files": true,
	"bootcmd":     true,
	"runcmd":      true,
}

// file is one write_files entry.
type file struct {
	Path        string `json:"path"`
	Encoding    string `json:"encoding,omitempty"`
	Owner       string `json:"owner,omitempty"`
	Permissions string `json:"permissions,omitempty"`
	Append      bool   `json:"append,omitempty"`
	Content     string `json:"content,omitempty"`
}

// cloudConfig is the subset of cloud-config CABPK emits.
type cloudConfig struct {
	WriteFiles []file `json:"write_files,omitempty"`
	BootCmd    []any  `json:"bootcmd,omitempty"`
	RunCmd     []any  `json:"runcmd,omitempty"`
}

// Options tunes what Render emits around the bootstrap data.
type Options struct {
	// ProviderID pins the kubelet's --provider-id.
	//
	// Cluster API matches a Node to its Machine by provider ID, but the bootstrap
	// data is generated per Machine before any host has been claimed, so the value
	// cannot come from the KubeadmConfig. kgenesis knows it by the time it pushes
	// the script, so it is written into the kubeadm configuration that is about to
	// be applied, under nodeRegistration.kubeletExtraArgs.
	//
	// A systemd drop-in would be the obvious alternative and does not work:
	// systemd lets EnvironmentFile= override Environment= whatever the order, and
	// the kubeadm packages install an /etc/default/kubelet that sets
	// KUBELET_EXTRA_ARGS. A drop-in is silently ignored on exactly the hosts this
	// provider targets. Going through kubeadm means the flag lands in
	// KUBELET_KUBEADM_ARGS, which nothing else competes for.
	ProviderID string
}

// kubeadmConfigKinds are the documents whose nodeRegistration decides how the
// kubelet on this machine registers itself.
var kubeadmConfigKinds = map[string]bool{
	"InitConfiguration": true,
	"JoinConfiguration": true,
}

const (
	kubeadmAPIGroupPrefix = "kubeadm.k8s.io/"
	providerIDFlag        = "provider-id"
)

// Render converts cloud-config user data into a bash script.
//
// It rejects any directive it does not implement rather than skipping it: a
// silently dropped `users` or `disk_setup` block would produce a host that looks
// bootstrapped but is not.
func Render(userData []byte, opts Options) ([]byte, error) {
	if err := checkUnsupported(userData); err != nil {
		return nil, err
	}

	cfg := &cloudConfig{}
	if err := yaml.Unmarshal(userData, cfg); err != nil {
		return nil, fmt.Errorf("parse cloud-config: %w", err)
	}

	var b bytes.Buffer
	b.WriteString("#!/usr/bin/env bash\n")
	b.WriteString("# Generated by kgenesis from Cluster API bootstrap data. Do not edit.\n")
	b.WriteString("set -euo pipefail\n\n")

	files, err := resolveFiles(cfg.WriteFiles)
	if err != nil {
		return nil, err
	}

	if opts.ProviderID != "" {
		if err := setProviderID(files, opts.ProviderID); err != nil {
			return nil, err
		}
	}

	if len(files) > 0 {
		b.WriteString("### write_files\n")
		for _, f := range files {
			b.WriteString(renderFile(f))
		}
		b.WriteString("\n")
	}

	for _, section := range []struct {
		name string
		cmds []any
	}{
		{"bootcmd", cfg.BootCmd},
		{"runcmd", cfg.RunCmd},
	} {
		if len(section.cmds) == 0 {
			continue
		}
		fmt.Fprintf(&b, "### %s\n", section.name)
		for _, raw := range section.cmds {
			line, err := renderCommand(raw)
			if err != nil {
				return nil, fmt.Errorf("%s: %w", section.name, err)
			}
			b.WriteString(line)
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}

	return b.Bytes(), nil
}

// checkUnsupported fails on any top level key this renderer does not implement.
func checkUnsupported(userData []byte) error {
	top := map[string]any{}
	if err := yaml.Unmarshal(userData, &top); err != nil {
		return fmt.Errorf("parse cloud-config: %w", err)
	}

	var unknown []string
	for k := range top {
		if !supported[k] {
			unknown = append(unknown, k)
		}
	}
	if len(unknown) == 0 {
		return nil
	}
	sort.Strings(unknown)
	return fmt.Errorf("cloud-config uses directives kgenesis does not implement: %s. "+
		"Express the same setup through preKubeadmCommands, postKubeadmCommands or files "+
		"in the KubeadmConfigSpec", strings.Join(unknown, ", "))
}

// heredocDelimiter cannot occur inside base64 output, so the payload never needs
// escaping regardless of what the file contains.
const heredocDelimiter = "KGENESIS_B64_EOF"

// resolvedFile is a write_files entry with its content already decoded, so the
// renderer and the provider ID injection both work on plain bytes.
type resolvedFile struct {
	file
	content []byte
}

func resolveFiles(entries []file) ([]*resolvedFile, error) {
	files := make([]*resolvedFile, 0, len(entries))
	for _, f := range entries {
		if f.Path == "" {
			return nil, fmt.Errorf("write_files entry has no path")
		}
		content, err := decodeContent(f.Content, f.Encoding)
		if err != nil {
			return nil, fmt.Errorf("write_files %s: %w", f.Path, err)
		}
		files = append(files, &resolvedFile{file: f, content: content})
	}
	return files, nil
}

func renderFile(f *resolvedFile) string {
	redirect := ">"
	if f.Append {
		redirect = ">>"
	}

	var b strings.Builder
	fmt.Fprintf(&b, "install -d -m 0755 %s\n", shellQuote(dirOf(f.Path)))
	fmt.Fprintf(&b, "base64 -d <<'%s' %s %s\n", heredocDelimiter, redirect, shellQuote(f.Path))
	b.WriteString(wrapBase64(f.content))
	fmt.Fprintf(&b, "%s\n", heredocDelimiter)

	if f.Owner != "" {
		fmt.Fprintf(&b, "chown %s %s\n", shellQuote(f.Owner), shellQuote(f.Path))
	}
	if f.Permissions != "" {
		fmt.Fprintf(&b, "chmod %s %s\n", shellQuote(f.Permissions), shellQuote(f.Path))
	}
	return b.String()
}

// decodeContent unwraps the encodings cloud-init defines for write_files.
func decodeContent(content, encoding string) ([]byte, error) {
	switch strings.ToLower(strings.TrimSpace(encoding)) {
	case "", "text/plain":
		return []byte(content), nil

	case "b64", "base64":
		return base64.StdEncoding.DecodeString(strings.TrimSpace(content))

	case "gz", "gzip":
		return gunzip([]byte(content))

	case "gz+b64", "gzip+base64", "gz+base64", "gzip+b64":
		raw, err := base64.StdEncoding.DecodeString(strings.TrimSpace(content))
		if err != nil {
			return nil, err
		}
		return gunzip(raw)

	default:
		return nil, fmt.Errorf("unsupported encoding %q", encoding)
	}
}

func gunzip(in []byte) ([]byte, error) {
	r, err := gzip.NewReader(bytes.NewReader(in))
	if err != nil {
		return nil, err
	}
	defer func() { _ = r.Close() }()
	return io.ReadAll(r)
}

// wrapBase64 emits the payload in fixed width lines so the script stays readable
// when an operator opens it on the host.
func wrapBase64(data []byte) string {
	const width = 76
	encoded := base64.StdEncoding.EncodeToString(data)

	var b strings.Builder
	for len(encoded) > width {
		b.WriteString(encoded[:width])
		b.WriteByte('\n')
		encoded = encoded[width:]
	}
	b.WriteString(encoded)
	b.WriteByte('\n')
	return b.String()
}

// renderCommand follows cloud-init semantics: a string is shell, a list is an
// argv vector that must not be re-interpreted by the shell.
func renderCommand(raw any) (string, error) {
	switch v := raw.(type) {
	case string:
		return v, nil

	case []any:
		parts := make([]string, 0, len(v))
		for _, item := range v {
			s, ok := item.(string)
			if !ok {
				return "", fmt.Errorf("argv entry %v is not a string", item)
			}
			parts = append(parts, shellQuote(s))
		}
		return strings.Join(parts, " "), nil

	default:
		return "", fmt.Errorf("entry %v is neither a string nor a list", raw)
	}
}

func dirOf(path string) string {
	i := strings.LastIndex(path, "/")
	if i <= 0 {
		return "/"
	}
	return path[:i]
}

func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
