package cloudinit

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"strings"
	"testing"

	"sigs.k8s.io/yaml"

	"github.com/blang/semver/v4"
	bootstrapv1 "sigs.k8s.io/cluster-api/api/bootstrap/kubeadm/v1beta2"
	"sigs.k8s.io/cluster-api/bootstrap/kubeadm/pkg/cloudinit"
	"sigs.k8s.io/cluster-api/util/secret"
)

// TestRenderCABPKControlPlaneInit feeds the renderer output generated by CABPK
// itself, so a change to the upstream cloud-config template shows up here rather
// than on a half-bootstrapped host.
func TestRenderCABPKControlPlaneInit(t *testing.T) {
	userData, err := cloudinit.NewInitControlPlane(&cloudinit.ControlPlaneInput{
		BaseUserData: cloudinit.BaseUserData{
			PreKubeadmCommands:  []string{"echo pre"},
			PostKubeadmCommands: []string{"echo post"},
			KubernetesVersion:   semver.MustParse("1.34.1"),
			AdditionalFiles: []bootstrapv1.File{{
				Path:        "/etc/kgenesis/marker",
				Owner:       "root:root",
				Permissions: "0644",
				Content:     "hello\nworld\n",
			}},
		},
		Certificates:         secret.Certificates{},
		ClusterConfiguration: "apiVersion: kubeadm.k8s.io/v1beta4\nkind: ClusterConfiguration\n",
		InitConfiguration:    "apiVersion: kubeadm.k8s.io/v1beta4\nkind: InitConfiguration\n",
	})
	if err != nil {
		t.Fatalf("generate CABPK user data: %v", err)
	}

	script, err := Render(userData, Options{})
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	got := string(script)

	for _, want := range []string{
		"set -euo pipefail",
		"/run/kubeadm/kubeadm.yaml",
		"/etc/kgenesis/marker",
		"echo pre",
		"kubeadm init --config /run/kubeadm/kubeadm.yaml",
		"echo post",
		SentinelPath,
	} {
		if !strings.Contains(got, want) {
			t.Errorf("rendered script is missing %q\n---\n%s", want, got)
		}
	}
}

// extractPayload returns the decoded content the script writes to path.
func extractPayload(t *testing.T, script, path string) string {
	t.Helper()

	marker := "> '" + path + "'\n"
	i := strings.Index(script, marker)
	if i < 0 {
		t.Fatalf("script does not write %s\n---\n%s", path, script)
	}
	rest := script[i+len(marker):]

	j := strings.Index(rest, heredocDelimiter)
	if j < 0 {
		t.Fatalf("heredoc for %s is not terminated\n---\n%s", path, script)
	}

	decoded, err := base64.StdEncoding.DecodeString(strings.Join(strings.Fields(rest[:j]), ""))
	if err != nil {
		t.Fatalf("payload for %s is not valid base64: %v", path, err)
	}
	return string(decoded)
}

func TestRenderWriteFileEncodings(t *testing.T) {
	var gz bytes.Buffer
	zw := gzip.NewWriter(&gz)
	if _, err := zw.Write([]byte("compressed payload")); err != nil {
		t.Fatalf("gzip write: %v", err)
	}
	if err := zw.Close(); err != nil {
		t.Fatalf("gzip close: %v", err)
	}

	userData := `#cloud-config
write_files:
-   path: /tmp/plain
    permissions: '0600'
    owner: root:root
    content: |
      line one
      line two
-   path: /tmp/b64
    encoding: "base64"
    content: ` + base64.StdEncoding.EncodeToString([]byte("decoded from base64")) + `
-   path: /tmp/gz
    encoding: "gzip+base64"
    content: ` + base64.StdEncoding.EncodeToString(gz.Bytes()) + `
-   path: /tmp/appended
    append: true
    content: more
`

	script, err := Render([]byte(userData), Options{})
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	got := string(script)

	for _, want := range []string{
		"chmod '0600' '/tmp/plain'",
		"chown 'root:root' '/tmp/plain'",
		">> '/tmp/appended'",
		"install -d -m 0755 '/tmp'",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("rendered script is missing %q\n---\n%s", want, got)
		}
	}

	for path, want := range map[string]string{
		"/tmp/plain": "line one\nline two\n",
		"/tmp/b64":   "decoded from base64",
		"/tmp/gz":    "compressed payload",
	} {
		if got := extractPayload(t, string(script), path); got != want {
			t.Errorf("%s: got %q, want %q", path, got, want)
		}
	}
}

func TestRenderRejectsUnsupportedDirectives(t *testing.T) {
	const userData = `#cloud-config
runcmd:
  - echo hi
users:
  - name: alice
disk_setup:
  /dev/sdb: {}
`
	_, err := Render([]byte(userData), Options{})
	if err == nil {
		t.Fatal("expected an error for unsupported directives, got nil")
	}
	for _, want := range []string{"disk_setup", "users"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("error does not name %q: %v", want, err)
		}
	}
}

func TestRenderArgvCommand(t *testing.T) {
	const userData = `#cloud-config
runcmd:
  - [ systemctl, restart, "kubelet" ]
  - echo "a string; runs through the shell"
`
	script, err := Render([]byte(userData), Options{})
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	got := string(script)

	if !strings.Contains(got, "'systemctl' 'restart' 'kubelet'") {
		t.Errorf("argv form was not quoted\n---\n%s", got)
	}
	if !strings.Contains(got, `echo "a string; runs through the shell"`) {
		t.Errorf("string form was not passed through verbatim\n---\n%s", got)
	}
}

func TestRenderInjectsProviderIDIntoKubeadmConfig(t *testing.T) {
	const providerID = "kgenesis://default/cp-1"

	// What CABPK emits for a control plane: a multi-document kubeadm config in
	// write_files, then kubeadm init in runcmd.
	const userData = `#cloud-config
write_files:
-   path: /run/kubeadm/kubeadm.yaml
    owner: root:root
    permissions: '0640'
    content: |
      ---
      apiVersion: kubeadm.k8s.io/v1beta4
      kind: ClusterConfiguration
      clusterName: lab
      ---
      apiVersion: kubeadm.k8s.io/v1beta4
      kind: InitConfiguration
      nodeRegistration:
        ignorePreflightErrors:
        - SystemVerification
runcmd:
  - kubeadm init --config /run/kubeadm/kubeadm.yaml
`

	script, err := Render([]byte(userData), Options{ProviderID: providerID})
	if err != nil {
		t.Fatalf("Render: %v", err)
	}

	written := extractPayload(t, string(script), "/run/kubeadm/kubeadm.yaml")

	docs, err := splitYAML([]byte(written))
	if err != nil {
		t.Fatalf("split the rewritten config: %v", err)
	}
	if len(docs) != 2 {
		t.Fatalf("expected 2 documents, got %d:\n%s", len(docs), written)
	}

	var init map[string]any
	if err := yaml.Unmarshal(docs[1], &init); err != nil {
		t.Fatalf("parse InitConfiguration: %v", err)
	}

	if init["kind"] != "InitConfiguration" {
		t.Fatalf("second document is %v, not InitConfiguration", init["kind"])
	}

	registration, ok := init["nodeRegistration"].(map[string]any)
	if !ok {
		t.Fatalf("nodeRegistration is missing:\n%s", written)
	}

	// The rest of nodeRegistration has to survive the rewrite.
	if _, ok := registration["ignorePreflightErrors"]; !ok {
		t.Errorf("the rewrite dropped ignorePreflightErrors:\n%s", written)
	}

	args, ok := registration["kubeletExtraArgs"].([]any)
	if !ok {
		t.Fatalf("kubeletExtraArgs is not a list, got %T:\n%s", registration["kubeletExtraArgs"], written)
	}
	if len(args) != 1 {
		t.Fatalf("expected one kubelet arg, got %v", args)
	}

	arg := args[0].(map[string]any)
	if arg["name"] != "provider-id" || arg["value"] != providerID {
		t.Errorf("kubelet arg is %v, want provider-id=%s", arg, providerID)
	}

	// The ClusterConfiguration document has no nodeRegistration and must be left
	// alone apart from formatting.
	var cluster map[string]any
	if err := yaml.Unmarshal(docs[0], &cluster); err != nil {
		t.Fatalf("parse ClusterConfiguration: %v", err)
	}
	if cluster["clusterName"] != "lab" {
		t.Errorf("ClusterConfiguration was altered: %v", cluster)
	}
}

// CABPK emits v1beta3 for Kubernetes below 1.31, where kubeletExtraArgs is a map.
func TestRenderInjectsProviderIDIntoV1beta3(t *testing.T) {
	const userData = `#cloud-config
write_files:
-   path: /run/kubeadm/kubeadm-join-config.yaml
    content: |
      apiVersion: kubeadm.k8s.io/v1beta3
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: role=worker
runcmd:
  - kubeadm join --config /run/kubeadm/kubeadm-join-config.yaml
`

	script, err := Render([]byte(userData), Options{ProviderID: "kgenesis://default/w-1"})
	if err != nil {
		t.Fatalf("Render: %v", err)
	}

	written := extractPayload(t, string(script), "/run/kubeadm/kubeadm-join-config.yaml")

	var join map[string]any
	if err := yaml.Unmarshal([]byte(written), &join); err != nil {
		t.Fatalf("parse JoinConfiguration: %v", err)
	}

	args, ok := join["nodeRegistration"].(map[string]any)["kubeletExtraArgs"].(map[string]any)
	if !ok {
		t.Fatalf("kubeletExtraArgs is not a map:\n%s", written)
	}
	if args["provider-id"] != "kgenesis://default/w-1" {
		t.Errorf("provider-id is %v", args["provider-id"])
	}
	// The existing entry must survive.
	if args["node-labels"] != "role=worker" {
		t.Errorf("the rewrite dropped node-labels: %v", args)
	}
}

// Applying a provider ID that lands nowhere would produce a machine Cluster API
// can never pair with its Node, so it has to be an error rather than a no-op.
func TestRenderFailsWhenThereIsNoKubeadmConfig(t *testing.T) {
	const userData = `#cloud-config
write_files:
-   path: /etc/motd
    content: nothing to patch here
runcmd:
  - "true"
`

	_, err := Render([]byte(userData), Options{ProviderID: "kgenesis://default/cp-1"})
	if err == nil {
		t.Fatal("expected an error when no kubeadm configuration is present")
	}
	if !strings.Contains(err.Error(), "provider ID") {
		t.Errorf("error does not explain the problem: %v", err)
	}
}

func TestRenderWithoutProviderIDLeavesTheConfigAlone(t *testing.T) {
	const userData = `#cloud-config
write_files:
-   path: /run/kubeadm/kubeadm.yaml
    content: |
      apiVersion: kubeadm.k8s.io/v1beta4
      kind: InitConfiguration
      nodeRegistration: {}
runcmd:
  - "true"
`

	script, err := Render([]byte(userData), Options{})
	if err != nil {
		t.Fatalf("Render: %v", err)
	}

	written := extractPayload(t, string(script), "/run/kubeadm/kubeadm.yaml")
	if strings.Contains(written, "kubeletExtraArgs") {
		t.Errorf("kubeletExtraArgs was added without a provider ID:\n%s", written)
	}
}
